services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-stats-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./pdf-storage:/app-pdfs
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
